### ISSUE TITLE
Django-Memoize doesn't work on type annotated functions

### ISSUE THREAD

**Issue by LaurensBosscher** [tvavrys/django-memoize#18]
I have a function with the following signature:

`@memoize(timeout=300)
def _start_sequence(self, exam: Exam):`

The moment I try to run the function with the annotation I get the following error:

`Function has keyword-only arguments or annotations, use getfullargspec() API which can support them`

If I remove the type annotation everything works as expected. Given that type annotations have become quite useful with Python 3.5 it would be intrestring to support them.

Unfortunately I see that the required function is only supported in Python 3: [inspect.getfullargspec](https://docs.python.org/3.5/library/inspect.html#inspect.getfullargspec) but with some Six magic we can probably make it work.

If you're interested and don't object to the inclusion of Six as an additional dependency I could create a pull request. Let me know!

**Comment by tvavrys** [comment]
Hi there!

I think we already have a pull request for it. https://github.com/tvavrys/django-memoize/pull/10/files

I just need to make some time soon and merge it.

**Comment by LaurensBosscher** [comment]
Awesome :)

**Comment by tvavrys** [comment]
Merged. Will bump the version soon. Closing.
