### ISSUE TITLE
Deprecation warning 

### ISSUE THREAD

**Issue by wrvdklooster** [tvavrys/django-memoize#32]
I see the following deprecation warning in Python 3.5.2:

`python3.5/site-packages/memoize/__init__.py:28: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  argspec = inspect.getargspec(f)`

**Comment by therefromhere** [comment]
See #24 for a potential fix for this

**Comment by wrvdklooster** [comment]
@therefromhere thanks, indeed the same issue.

Closing this as duplicate of #24
