### ISSUE TITLE
Is memoize refresh possible ?

### ISSUE THREAD

**Issue by toxinu** [tvavrys/django-memoize#5]
Hi,

Is memoize refresh possible ? In order to doesn't have cache interrupt.
For example, I set a one day cache and a task that start 10 minutes before cache invalidation to refresh it by myself. But if I delete it and re-run the function, I'll have interruption. Am I clear ? :smile: 

Thank you.

**Comment by mourkeita** [comment]
what kind of cache did you deploy ?

**Comment by tvavrys** [comment]
What do you mean by "interruption"?

**Comment by socketubs** [comment]
@tvavrys I mean that a user could potientially request the method I am refreshing.
In fact I want to know if I can do something like that:

```
@memoize(timeout=60 * 5)
def hello():
  r = requests.get('http://google.fr')

# I run method at django runtime because I don't want my users wait for it
hello()
# Method is cached for 5 minutes

# Just before timeout I want to do something like that
memoize.refresh(hello)

# Instead of 
memoize.delete(hello)
# Here, a user can request hello() method before me (or during)
hello()
```

This is not easy to explain. But this is the same thing that `cache.set` in django core, which when you specify a existing key, it just update the value.

Thank you @tvavrys :smile:

**Comment by tvavrys** [comment]
@socketubs 

I see. Well, django-memoize doesn't have a `refresh` method and I think that it's not necessary.

Basically, your memoize.refresh does this:

```
def refresh(func):
    memoize.delete(func)
    func()
refresh(hello)
```

So why don't you run `func()` right after the `delete` call?

**Comment by socketubs** [comment]
Because if my cached method take 10 minutes to return result, users can request view that run it during this time. Then there will be multiple same methods running during 10 minutes.

I imagine a memoize method like that:
```
memoize.update(hello)
```

That just run method without deleting cache and update cache value when method as returned.
Then during 10 minutes memoize continue returning cache.

**Comment by tvavrys** [comment]
That is not possible at the moment. You can use inheritance. Create a new Memoizer class and create a new `update` method.

```
def update(self, func, *args, **kwags):
    cache_key = decorated_function.make_cache_key(f, *args, **kwargs)
    rv = f(*args, **kwargs)
    self.set(cache_key, rv, timeout=decorated_function.cache_timeout)
```

**Comment by socketubs** [comment]
I supposed `django-memoize` was nice build to allow easy inheritance but this is just a simple feature request if you think it could usefull.

Thank you for the snippet ! :smile:

**Comment by tvavrys** [comment]
I'll think about it. It sounds reasonable.

Thanks.

**Comment by chescales** [comment]
Hi @tvavrys, I would also use this functionality if it would be in the app. If I have some time I may try to make a pull request. Thanks!
