### ISSUE TITLE
*args are ignored by memoize. 

### ISSUE THREAD

**Issue by patgmiller** [tvavrys/django-memoize#8]
Is it intentional that the `*args` after the declared arguments are ignored by the `memoize` decorator, or is that a bug? Below is an example in an ipython shell with `python==2.7.6`, `django==1.4.22` of how memoize isn't taking into account the `*args`. 

```python
In [16]: @memoize()
def func(*args, **kwargs):
    return args, kwargs
   ....:

In [17]: func(1)
Out[17]: ((1,), {})

In [18]: func(2)
Out[18]: ((1,), {})

In [19]: func(1, 2)
Out[19]: ((1,), {})

In [20]: func(1, one=1)
Out[20]: ((1,), {'one': 1})
```

**Comment by patgmiller** [comment]
I added a pull request which resolves this and includes updated tests. 
Pull Request #9

**Comment by tvavrys** [comment]
Solved.
